[General]
type=image
background=/usr/share/wallpapers/HoltOS/contents/images/1920x1080.png
glow=/usr/share/sddm/themes/holtos/glow.png
otter=/usr/share/sddm/themes/holtos/otter.png
lockup=/usr/share/sddm/themes/holtos/lockup.png
needsFullUserModel=false
