[Icon Theme]
Name=HoltOS
Comment=HoltOS glass icons, falling back to Breeze
Inherits=breeze-dark,breeze_cursors,hicolor
Example=folder
Directories=16x16/apps,16x16/mimetypes,16x16/places,22x22/apps,22x22/mimetypes,22x22/places,24x24/apps,24x24/mimetypes,24x24/places,32x32/apps,32x32/mimetypes,32x32/places,48x48/apps,48x48/mimetypes,48x48/places,64x64/apps,64x64/mimetypes,64x64/places,96x96/apps,96x96/mimetypes,96x96/places,128x128/apps,128x128/mimetypes,128x128/places,256x256/apps,256x256/mimetypes,256x256/places

[16x16/apps]
Size=1616
Context=Applications
Type=Fixed

[16x16/mimetypes]
Size=1616
Context=MimeTypes
Type=Fixed

[16x16/places]
Size=1616
Context=Places
Type=Fixed

[22x22/apps]
Size=2222
Context=Applications
Type=Fixed

[22x22/mimetypes]
Size=2222
Context=MimeTypes
Type=Fixed

[22x22/places]
Size=2222
Context=Places
Type=Fixed

[24x24/apps]
Size=2424
Context=Applications
Type=Fixed

[24x24/mimetypes]
Size=2424
Context=MimeTypes
Type=Fixed

[24x24/places]
Size=2424
Context=Places
Type=Fixed

[32x32/apps]
Size=3232
Context=Applications
Type=Fixed

[32x32/mimetypes]
Size=3232
Context=MimeTypes
Type=Fixed

[32x32/places]
Size=3232
Context=Places
Type=Fixed

[48x48/apps]
Size=4848
Context=Applications
Type=Fixed

[48x48/mimetypes]
Size=4848
Context=MimeTypes
Type=Fixed

[48x48/places]
Size=4848
Context=Places
Type=Fixed

[64x64/apps]
Size=6464
Context=Applications
Type=Fixed

[64x64/mimetypes]
Size=6464
Context=MimeTypes
Type=Fixed

[64x64/places]
Size=6464
Context=Places
Type=Fixed

[96x96/apps]
Size=9696
Context=Applications
Type=Fixed

[96x96/mimetypes]
Size=9696
Context=MimeTypes
Type=Fixed

[96x96/places]
Size=9696
Context=Places
Type=Fixed

[128x128/apps]
Size=128128
Context=Applications
Type=Fixed

[128x128/mimetypes]
Size=128128
Context=MimeTypes
Type=Fixed

[128x128/places]
Size=128128
Context=Places
Type=Fixed

[256x256/apps]
Size=256256
Context=Applications
Type=Fixed

[256x256/mimetypes]
Size=256256
Context=MimeTypes
Type=Fixed

[256x256/places]
Size=256256
Context=Places
Type=Fixed
